### PR TITLE
Updated dependencies / moved to Webpack 2.x

### PR DESCRIPTION
**Pull request by mtompkins**
Offering you a PR - simple updates to dependencies.
Still some problems in the test module.

Also moved out of XO (wouldn't play nice) to ESLint directly.

Feel free to reject or accept anything you like.

### CODE REVIEW

**Comment by tmsh** [comment]
Wow cool! Thanks for the PR. I was thinking about exploring react-desktop in the future (mentioning in case you haven't seen it). But maybe I'll stick to react-photonkit thanks to your interest and updates.

**Comment by mtompkins** [comment]
I have seen it. I think it misses a couple things but they all have some shortfalls.
FYI, the compiled version is throwing a `Super expression must either be null or a function, not undefined` ... trying to hunt it down.

I don't think it's from anything I did, I just updated mod's...will advise or if you happen to see it.

**Comment by mtompkins** [comment]
Found it - out of habit I changed a function to `default export` .. I'll send you a followup PR.

**Comment by tmsh** [comment]
Cool, thanks!

**Comment by mtompkins** [comment]
Quite welcome - maybe one day we'll get to collaborate.
As you mentioned react-desktop, just making sure you've seen this: 
https://github.com/sindresorhus/awesome-electron#components

**Pull request merged**
